version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - vote-net
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - vote-net
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - vote-net
volumes:
  db_data:

networks:
  vote-net:
