version: '3.8'

networks:
  frontend:
  backend:

services:
  vote:
    build: ./vote
    networks:
      - backend
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    expose:
      - "80"  # Expose uniquement en interne, pas de port sur host

  result:
    build: ./result
    networks:
      - backend
    environment:
      - DB_HOST=db
      - DB_USER=voteuser
      - DB_PASSWORD=vote123
      - DB_NAME=votedb
    depends_on:
      - db
    expose:
      - "80"

  worker:
    build: ./worker
    networks:
      - backend
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
      - DB_USER=voteuser
      - DB_PASSWORD=vote123
      - DB_NAME=votedb
    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine
    networks:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: voteuser
      POSTGRES_PASSWORD: vote123
      POSTGRES_DB: votedb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - vote
      - result
    networks:
      - frontend
      - backend

volumes:
  pgdata:




